### ISSUE TITLE
create searchbar

### ISSUE THREAD

**Issue by michaelbolgar** [michaelbolgar/MovieApp#4]

**Comment by michaelbolgar** [comment]
Серчбар должен быть реализован как отдельная вью в отдельном файле. Зашить внутрь кнопку для старта сёрча (например повесить картинку лупы справа, вместо той что слева), крестик для удаления всего текста, автоматическое сокрытие клавиатуры при начале сёрча (спроси меня про это отдельно)

**Comment by YO1901** [comment]
Мы хотим делать поиск по кнопке? Не как везде в  iOS поиск при вводе знаков с клавиатуры?

**Comment by michaelbolgar** [comment]
да, дополнительно кнопку с активацией поиска. Это становится актуально в тот момент, если например в момент ввода текста у юзера отвалился интернет и он не получил никакого ответа от сервера. На экране не будет никак отображено, что запрос не отработал, а если он тыкнет кнопку -- либо повторный запрос даст результат, либо станет понятно, что что-то идёт не так
